import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NextAuthSessionProvider from "@/providers/session-provider";

const poppinsSans = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body
        className={`${poppinsSans.variable} ${geistMono.variable} h-full font-sans antialiased`}
      >
        <NextAuthSessionProvider>
          <div className="flex h-full flex-col">
            <Header />

            <main className="w-full max-w-[1920px] flex-1 self-center overflow-y-auto">
              <Providers>{children}</Providers>
            </main>
          </div>
        </NextAuthSessionProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
